"""empty message

Revision ID: 72d8d4d8219
Revises: 30a1e027aefa
Create Date: 2017-10-31 19:52:20.538000

"""

# revision identifiers, used by Alembic.
revision = '72d8d4d8219'
down_revision = '30a1e027aefa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyvojari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vyvojar', sa.String(length=64), nullable=False),
    sa.Column('pocetTitulu', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_vyvojari')
    )
    op.create_index('ix_vyvojari_vyvojar', 'vyvojari', ['vyvojar'], unique=True)
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index('ix_vyvojari_vyvojar', table_name='vyvojari')
    op.drop_table('vyvojari')
    ### end Alembic commands ###
